name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        ports: ["5432:5432"]
        env:
          POSTGRES_PASSWORD: password
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      RAILS_ENV: test
      PGHOST: localhost
      PGUSER: postgres
      PGPASSWORD: password
      DATABASE_URL: postgres://postgres:password@localhost:5432/test
      STANDARD_RUBY_OPTS: --no-autocorrect

    steps:
      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.4.2"

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3

      - name: Setup DB
        run: |
          bin/rails db:prepare

      - name: Run StandardRB
        run: bundle exec standardrb $STANDARD_RUBY_OPTS

      - name: Run tests
        run: bin/rails test
